### ISSUE TITLE
Spell it right!

### ISSUE THREAD

**Issue by Lakshita2002** [Divyanshu23/IIEP-Projects#1]
Shouldn't it be **projects**, instead of **projetcs**
You might want to look into that, unless of course it is **projetcs**

**Comment by Divyanshu23** [comment]
Thanks @Lakshita2002 for pointing this out. The typo has been fixed.

**Comment by Lakshita2002** [comment]
@Divyanshu23 well well, good job on that sir lol
I guess it's ok to be a bit informal on GitHub lmao
